SELECT EXTRACT(HOUR FROM datetime) AS hour, COUNT(*) AS count
FROM animal_outs
WHERE EXTRACT(HOUR FROM datetime) BETWEEN '9' AND '19'
GROUP BY EXTRACT(HOUR FROM datetime)
ORDER BY EXTRACT(HOUR FROM datetime) ASC;