SELECT EXTRACT(YEAR FROM ym) AS year, ROUND(AVG(pm_val1), 2) AS pm10, ROUND(AVG(pm_val2), 2) AS `pm2.5`
FROM air_pollution
WHERE LOCATION1 = '경기도' AND LOCATION2 = '수원'
GROUP BY EXTRACT(YEAR FROM ym)
ORDER BY year ASC;